name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: "4.3"
  EXPORT_NAME: "pati-patni-ki-ladai"

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-24.04

    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        run: |
          mkdir -p ~/.config/godot
          mkdir -p ~/.local/share/godot/export_templates

          cp /root/.config/godot/editor_settings-4.3.tres \
             ~/.config/godot/editor_settings-4.3.tres

          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

          sed -i 's|export/android/java_sdk_path = ".*"|export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"|g' \
            ~/.config/godot/editor_settings-4.3.tres

          sed -i 's|export/android/android_sdk_path = ".*"|export/android/android_sdk_path = "/usr/lib/android-sdk"|g' \
            ~/.config/godot/editor_settings-4.3.tres

      - name: Check Android SDK and Java
        run: |
          java -version
          test -d /usr/lib/jvm/java-17-openjdk-amd64
          test -d /usr/lib/android-sdk
          test -f /usr/lib/android-sdk/platform-tools/adb
          echo "Java SDK and Android SDK found."

      - name: Check project
        run: |
          godot --headless --path . --editor --quit

      - name: Build Android APK
        run: |
          mkdir -p build/android

          godot --headless --verbose \
            --path . \
            --export-debug "Android Debug" \
            "build/android/${EXPORT_NAME}.apk"

      - name: Check APK
        run: |
          ls -lh build/android
          test -f "build/android/${EXPORT_NAME}.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pati-patni-ki-ladai-APK
          path: build/android/*.apk
          if-no-files-found: error
